apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securepipeline

resources:
  - namespace-config.yaml
  - deployment.yaml
  - networking.yaml
  - security-policies.yaml

labels:
  app.kubernetes.io/part-of: securepipeline
  app.kubernetes.io/managed-by: kustomize
